dockurr/views.py
from flask import (Blueprint, abort, redirect, g,
                   render_template, request, session, url_for, flash)

from dockurr.models import User, Container, ContainerStatus, db
from dockurr.tasks import container_controller

bp = Blueprint('views', __name__)


@bp.before_request
def check_auth():
    on_auth_page = request.endpoint == 'views.auth'
    logged_in = session.get('uid') is not None
    if not on_auth_page and not logged_in:
        return redirect(url_for('views.auth'))
    elif on_auth_page and logged_in:
        return redirect(url_for('views.dashboard'))
    g.uid = session.get('uid')
    g.username = session.get('username')
    g.CS = ContainerStatus


@bp.route('/')
def home():
    return redirect(url_for('views.dashboard'))


@bp.route('/logout')
def logout():
    session.pop('uid')
    session.pop('username')
    flash('Bye-bye', 'info')
    return redirect(url_for('views.auth'))


@bp.route('/auth', methods=['GET', 'POST'])
def auth():
    if request.method == 'POST':
        username = request.form.get('username')
        password = request.form.get('password')

        if not username or not password:
            abort(400)

        if not User.query.filter_by(username=username).first():
            user = User(username, password)
            db.session.add(user)
            db.session.commit()
            flash('New user created', 'info')
        else:
            uid = User.authenticate(username, password)
            if uid is not None:
                session['uid'] = uid
                session['username'] = username
                return redirect(url_for('views.home'))
            flash('Invalid username or password', 'danger')
    return render_template('auth.html')


@bp.route('/dashboard')
def dashboard():
    containers = Container.query.filter_by(user_id=g.uid).all()
    return render_template('dashboard.html', containers=containers)


@bp.route('/create-container', methods=['GET', 'POST'])
def create_container():
    if request.method == 'POST':
        name = request.form.get('name')
        image = request.form.get('image')
        container_port = request.form.get('container_port')
        if not (name and image and container_port):
            abort(400)
        container = Container(g.uid, name, image, container_port)
        db.session.add(container)
        db.session.commit()
        container_controller.start_container.delay(
            container.id)  # type: ignore
        flash(f'Container {name} created successfully, will start right away',
              'success')
        return redirect(url_for('views.dashboard'))
    return render_template('create_container.html')


@bp.route('/start-container/<int:id>')
def start_container(id):
    Container.query.filter_by(id=id, user_id=g.uid).first_or_404()
    flash(f'Container {id} will be started', 'info')
    container_controller.start_container.delay(id)  # type: ignore
    return redirect(url_for('views.dashboard'))


@bp.route('/stop-container/<int:id>')
def stop_container(id):
    Container.query.filter_by(id=id, user_id=g.uid).first_or_404()
    flash(f'Container {id} will be stopped', 'info')
    container_controller.stop_container.delay(id)  # type: ignore
    return redirect(url_for('views.dashboard'))


@bp.route('/delete-container/<int:id>')
def delete_container(id):
    Container.query.filter_by(id=id, user_id=g.uid).first_or_404()
    container_controller.delete_container.delay(id)  # type: ignore
    flash(f'Container {id} will be deleted', 'info')
    return redirect(url_for('views.dashboard'))


@bp.route('/schedule-container/<int:id>', methods=['GET', 'POST'])
def schedule_container(id):
    container = Container.query.filter_by(id=id,
                                          user_id=g.uid).first_or_404()
    if request.method == 'POST':
        scheduled = request.form.get('scheduled')
        start_hour = request.form.get('start_hour')
        start_minute = request.form.get('start_minute')
        stop_hour = request.form.get('stop_hour')
        stop_minute = request.form.get('stop_minute')

        if scheduled and start_hour and start_minute \
                and stop_hour and stop_minute:
            container.set_schedule(start_hour, start_minute,
                                   stop_hour, stop_minute)
            flash(f'Container {container.name} scheduled', 'success')
        else:
            container.unset_schedule()
            flash(f'Container {container.name} unscheduled', 'info')
        db.session.commit()
    return render_template('schedule_container.html', container=container)


@bp.route('/container-billing/<int:id>')
def container_billing(id):
    container = Container.query.filter_by(user_id=g.uid, id=id).first_or_404()
    return render_template('container_billing.html', container=container)


@bp.route('/user-billing')
def user_billing():
    user = User.query.filter_by(id=g.uid).first_or_404()
    return render_template('user_billing.html', user=user)

dockurr/templates/auth.html
{% extends "skel.html" %}
{% block title %}Authentication{% endblock %}
{% block container %}
  <form class="d-flex justify-content-center flex-column align-items-center position-absolute top-50 start-50 translate-middle" method="post">
    <div class="text-center">
      <img class="" src="{{ url_for('static', filename='logo.svg') }}" alt="" height="150">
      <h1 class="mt-4">Dockurr</h1>
      <p>
      Please log in to continue.<br> If a username does not exists,
      an account will be created with the provided password.
      </p>
    </div>
    <div class="form-outline mb-3 w-lg-50">
      <label class="form-label">Username</label>
      <input type="text" class="form-control" name="username" />
    </div>

    <div class="form-outline mx-4 mb-3 w-lg-50">
      <label class="form-label">Password</label>
      <input type="password" class="form-control" name="password" />
    </div>

    <button type="submit" class="btn btn-primary btn-block mb-4">Sign in</button>
  </form>
{% endblock %}

dockurr/templates/container_billing.html
{% extends "skel.html" %}

{% block title %}Container Billing{% endblock %}


{% block container %}
  <div class="d-flex justify-content-center align-items-center flex-column">
    <h1>Container Bills: {{ container.name }}
    </h1>
    <h5>Total cost: {{ container.bills.total | format_price }}</h5>
    <p>Price per billed minute is {{ config.DOCKURR_PRICES['container_usage_per_minute'] | format_price }}</p>
  </div>
  <h3>History</h3>
  <div class="table table-responsive">
    <table class="table table-striped">
      <thead class="table col-sm-10">
        <tr>
          <th scope="col">Start Time</th>
          <th scope="col">Stop Time</th>
          <th scope="col">Minutes</th>
          <th scope="col">Cost</th>
        </tr>
      </thead>
      <tbody>
        {% for bill in container.bills.history %}
          <tr>
            <td>{{ bill['start'].strftime('%Y-%m-%d %H:%M:%S') }}</td>
            <td>{{ bill['stop'].strftime('%Y-%m-%d %H:%M:%S') }}</td>
            <td>{{ '%.2f' | format(bill['minutes']) }}</td>
            <td>{{ bill['cost'] | format_price }}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
{% endblock %}

dockurr/templates/create_container.html
{% extends "skel.html" %}

{% block title %}Create Container{% endblock %}

{% block container %}
<h1 class="py-2 text-truncate text-center">Create Container</h1>
<div class="container">
  <div class="row">
    <div class=" col-xl-5 mx-auto text-center form p-4">
      <div class="px-2 text-start">
        <form action="" class="justify-content-center" method="post">
          <div class="form-group py-2">
            <label class="sr-only">Container Name</label>
            <input type="text" class="form-control" placeholder="Jane Doe" name="name" value="My nginx server" required>
          </div>
          <div class="form-group py-2">
            <label class="sr-only">From Image</label>
            <input type="text" class="form-control" placeholder="nginx" name="image" value="nginx" required>
          </div>
          <div class="form-group py-2">
            <label class="sr-only">Container Port</label>
            <input type="text" class="form-control" placeholder="80" name="container_port" value="80" required>
          </div>
          <div class="d-flex justify-content-center align-items-center">
            <button type="submit" class="m-3 btn btn-primary">Create</button>
          </div>
        </form>
      </div>
    </div>

  </div>
</div>
{% endblock %}

dockurr/templates/dashboard.html
{% extends "skel.html" %}
{% block title %}Dashboard{% endblock %}
{% block meta %}
  <meta http-equiv="refresh" content="2">  
{% endblock %}
{% block container %}
  <div class="mt-5 d-flex flex-column flex-lg-row justify-content-between align-items-center">
    <h5 class="fw-bold">Welcome, <i>{{ g.username }}</i>!</h5>
    <a class="btn btn-success my-1"
    role="button"
    href="{{ url_for("views.create_container") }}">Create container</a>
  </div>
  {% for container in containers %}
    <div class="card my-4">
      <div class="card-header">
        <h3><b>{{ container.name }}</b></h3>
      </div>
      <div class="card-body">
        <div class="row">
          <div class="col-sm-3">Image:</div>
          <div class="col">{{ container.image }}</div>
        </div>
        <div class="row">
          <div class="col-sm-3">Internal ID:</div>
          <samp class="col d-inline-block text-truncate" style="max-width: 40vw">
            {{ container.internal_id }}
          </samp>
        </div>
        <div class="row font-sm">
          <div class="col-sm-3">Status:</div>
          <div class="col">{{ container.status }}</div>
        </div>
        <div class="row font-sm">
          <div class="col-sm-3">Forwarded port:</div>
          <div class="col">
            container:{{ container.container_port }} 
            &harr;
            <a href="http://localhost:{{container.public_port}}" class="text-decoration-none" target="_blank">
              host:{{container.public_port}}
            </a>
          </div>
        </div>
        <div class="d-flex col pt-3 pb-1 justify-content-between flex-lg-col">
          <div>
            <a class="btn btn-primary mb-1 {% if not container.status.runnable %}disabled{% endif %}"
               href="{{ url_for('views.start_container', id=container.id) }}"
               type="button"
               disabled>Start</a>
            <a class="btn btn-warning text-dark mb-1 {% if not container.status.stoppable %}disabled{% endif %}"
               href="{{ url_for('views.stop_container', id=container.id) }}">Stop</a>
            <a class="btn btn-danger mb-1"
               href="{{ url_for('views.delete_container', id=container.id) }}" onclick="return confirm('Are you sure?')">Delete</a>
          </div>
          <div>
            <a class="btn btn-primary mb-1"
               href="{{ url_for('views.schedule_container', id=container.id) }}">Schedule</a>
            <a class="btn btn-warning text-dark mb-1"
               href="{{ url_for('views.container_billing', id=container.id) }}">View Billing</a>
          </div>
        </div>
      </div>
    </div>
  {% endfor %}
{% endblock %}

dockurr/templates/schedule_container.html
{% extends "skel.html" %}

{% block title %}Schedule Container{% endblock %}

{% block container %}
  <form method="post" class="d-flex justify-content-center flex-column align-items-center" x-data="{ enabled: {{ container.scheduled|tojson }} }">
    <h1 class="text-center">Schedule Container: <br>{{container.name}}</h1>
    <div class="mt-5 mb-4 form-check">
      <input type="checkbox" class="form-check-input" id="checkEnableScheduling" name="scheduled" x-model="enabled">
      <label class="form-check-label" for="checkEnableScheduling">Enable scheduling</label>
    </div>
    <div class="d-flex container justify-content-center flex-column align-items-center">
      <div class="row">
        <div class="col-6" x-show="enabled">
          <label>Start hour</label>
          <input type="number" name="start_hour" class="form-control" value="{{ container.start_hour }}" />
          <br />
        </div>
        <div class="col-6" x-show="enabled">
          <label>Start minute</label>
          <input type="number" name="start_minute" class="form-control" value="{{ container.start_minute }}">
          <br />
        </div>
      </div>
      <div class="row">
        <div class="col-6" x-show="enabled">
          <label>Stop hour</label>
          <input type="number" name="stop_hour" class="form-control" value="{{ container.stop_hour }}">
          <br />
        </div>
        <div class="col-6" x-show="enabled">
          <label>Stop minute</label>
          <input type="number" name="stop_minute" class="form-control" value="{{ container.stop_minute }}">
          <br />
        </div>
      </div>
      <div class="d-flex justify-content-center align-item-center col-6">
        <button class="my-3 btn btn-primary" type="submit">Schedule</button>
      </div>
  </form>
{% endblock %}

dockurr/templates/skel.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    {% block meta %}{% endblock %}
    <title>dockurr: {% block title %}{% endblock %}</title>
    <link href="
                https://cdn.jsdelivr.net/npm/bootswatch@5.2.3/dist/sketchy/bootstrap.min.css
                " rel="stylesheet">
    <link rel="stylesheet" href="{{ url_for('static', filename='styles.css') }}">

  </head>
  <body>
    {% if g.uid %}
      <nav class="navbar navbar-expand-lg d-flex navbar-light bg-info-emphasis justify-content-between px-4">
        <div class="d-flex align-items-center w-full">
          <img class="mr-3"
               src="{{ url_for('static', filename='logo.svg') }}"
               alt=""
               height="30">
          <a class="navbar-brand  mt-1 mx-2"  href="{{ url_for('views.dashboard') }}">Dockurr</a>
        </div>
        <div>
          <a class="btn btn-secondary my-1"
             role="button"
             href="{{ url_for("views.user_billing") }}">User Billing</a>
          <a class="btn btn-danger my-1"
             role="button"
             href="{{ url_for("views.logout") }}">Logout</a>
        </div>
      </nav>
    {% endif %}
    <div class="container my-5">
      {% with messages = get_flashed_messages(with_categories=true) %} {% if
        messages %} {% for category, message in messages %}
          <div class="alert alert-{{category}}" role="alert">{{ message }}</div>
        {% endfor %}
      {% endif %}
    {% endwith %}

    {% block container %}{% endblock %}
    </div>

    <script
        src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4"
        crossorigin="anonymous"
        ></script>
    <script defer src="https://cdn.jsdelivr.net/npm/alpinejs@3.x.x/dist/cdn.min.js"></script>
  </body>
</html>

dockurr/templates/user_billing.html
{% extends "skel.html" %}

{% block title %}My Bills{% endblock %}

{% set user_bills = user.bills %}

{% block container %}
  <div class="d-flex justify-content-center align-items-center flex-column">
    <h1>My Billing</h1>
    <h5>Total cost: {{ user_bills.total | format_price }}</h5>
  </div>
  <h3>Per-container Cost</h3>
  <div class="table table-responsive">
    <table class="table table-striped">
      <thead class="table col-sm-10">
        <tr>
          <th scope="col">Container name</th>
          <th scope="col">Cost</th>
        </tr>
      </thead>
      <tbody>
        {% for container_name, bills in user_bills.summary.items() %}
          <tr>
            <td>{{ container_name }}</td>
            <td>{{ bills.total | format_price }}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
{% endblock %}